.\"                                      Hey, EMACS: -*- nroff -*-
.TH KRYSTALDROP 6 "October 27, 2002"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.SH NAME
krystaldrop \- a puzzle/action game
.SH SYNOPSIS
.B kdrop
.RI "(no options yet)"
.SH DESCRIPTION
.B Krystal Drop
is a puzzle/action game à la Puzzle Bubble or Tetris Attack.
It is actually a GPL clone of NeoGeo's Magical Drop 2.
.br
.PP
.SH OPTIONS
The configuration is specified at compile-time, and by means of 
\fI~/kdrop.xml\fP, \fI~/.kdroprc\fP, \fI./kdrop.xml\fP or \fI/etc/kdrop.xml\fP.
The search is performed in that order, and stops on the first
valid configuration file found.

.SH AUTHOR
This manual page was (hastily) written by krys <krys@cnedra.org>,
for the Debian GNU/Linux system, but may be used by others.
